export default {
  LoginScreen: 'LoginScreen',
  HomeScreen: 'HomeScreen',
  AccessSettingScreen: 'AccessSettingScreen',
  AppointmentBookedScreen: 'AppointmentBookedScreen',
  ConfirmPayScreen: 'ConfirmPayScreen',
  ConsentScreen: 'ConsentScreen',
  DateTimeFilterScreen: 'DateTimeFilterScreen',
  InsuranceMemberIDScreen: 'InsuranceMemberIDScreen',
  InsuranceTypeScreen: 'InsuranceTypeScreen',
  InsuranceVerifiedScreen: 'InsuranceVerifiedScreen',
  PaymentTypeScreen: 'PaymentTypeScreen',
  PersonalInfoScreen: 'PersonalInfoScreen',
  QRCodeScreen: 'QRCodeScreen',
  SelectProviderScreen: 'SelectProviderScreen',
  SendSMSScreen: 'SendSMSScreen',
  SettingsScreen: 'SettingsScreen',
  AppointmentTypeScreen: 'AppointmentTypeScreen',
}
